In [1]:
# Final Project : CPBL Champion - Pattern Mining
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori

In [2]:
# Read File

raw_data_cpbl_s0 = pd.read_excel('cpbl-all.xlsx', index_col=0, sheet_name = 0) 
raw_data_cpbl_s0 = raw_data_cpbl_s0.replace(np.nan, False)
raw_data_cpbl_s0 = raw_data_cpbl_s0.replace('Y', True)

raw_data_cpbl_s1 = pd.read_excel('cpbl-all.xlsx', index_col=0, sheet_name = 1)  # sheet_name(1) = preprocessing version
raw_data_cpbl_s1 = raw_data_cpbl_s1.replace(np.nan, False)
raw_data_cpbl_s1 = raw_data_cpbl_s1.replace('Y', True)

raw_data_cpbl_s0

,G1W,G2W,G3W,G4W,G5W,G6W,G7W,G1L,G2L,G3L,...,T-REX 1st,Uni-Lions 2nd,Rakuten 2nd,Fubon 2nd,Brothers 2nd,Dragons 2nd,Whale 2nd,Tiger 2nd,Hank 2nd,T-REX 2nd
職棒年,,,,,,,,,,,,,,,,,,,,,
1990,True,False,True,True,False,True,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
1991,False,True,False,True,True,False,True,True,False,True,...,False,False,False,False,False,True,False,False,False,False
1992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1993,True,True,False,True,False,True,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
1994,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1996,True,False,True,True,False,True,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
1997,False,False,True,True,True,True,False,True,True,False,...,False,False,False,False,False,False,False,False,True,False
1998,True,False,True,False,False,True,True,False,True,False,...,False,False,False,True,False,False,False,False,False,False
1999,True,True,True,False,True,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2000,True,False,True,True,False,False,True,False,True,False,...,False,False,False,True,False,False,False,False,False,False
2001,True,False,False,False,True,True,True,False,True,True,...,False,True,False,False,False,False,False,False,False,False
2002,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2003,True,False,True,True,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
2004,True,True,False,False,False,True,True,False,False,True,...,False,True,False,False,False,False,False,False,False,False
2005,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2006,True,True,True,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2007,True,True,False,True,False,False,True,False,False,True,...,False,False,True,False,False,False,False,False,False,False
2008,False,True,False,True,True,False,True,True,False,True,...,False,False,False,False,True,False,False,False,False,False
2009,True,True,False,True,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2010,True,True,True,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2011,True,True,False,True,True,False,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
2012,True,True,False,True,True,False,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
2013,True,True,True,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2014,True,True,True,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2015,True,False,False,False,True,True,True,False,True,True,...,False,False,False,False,True,False,False,False,False,False
2016,False,False,True,True,True,True,False,True,True,False,...,False,False,False,False,True,False,False,False,False,False
2017,True,False,True,True,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2018,True,True,False,False,True,True,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
2019,True,False,True,True,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2020,True,False,False,False,True,True,True,False,True,True,...,False,False,False,False,True,False,False,False,False,False
2021,True,True,True,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [3]:
# Part1 : 對戰組合Mining
part1 = raw_data_cpbl_s0[['Uni-Lions 1st', 'Rakuten 1st', 'Fubon 1st', 'Brothers 1st', 'Dragons 1st', 'Whale 1st', 'Tiger 1st', 'Hank 1st', 'T-REX 1st', 
                       'Uni-Lions 2nd', 'Rakuten 2nd', 'Fubon 2nd', 'Brothers 2nd', 'Dragons 2nd', 'Whale 2nd', 'Tiger 2nd', 'Hank 2nd', 'T-REX 2nd']]
min_support = 0.03125   # 0.03125 = 1/32
 

frequent_1 = apriori(part1, min_support=min_support, use_colnames=True)
frequent_1 = frequent_1.sort_values('support', ascending=False)
frequent_1['total'] = frequent_1['support'] / 0.03125
frequent_1

    support                       itemsets  total
0   0.31250                (Uni-Lions 1st)   10.0
3   0.25000                 (Brothers 1st)    8.0
8   0.25000                 (Brothers 2nd)    8.0
1   0.21875                  (Rakuten 1st)    7.0
5   0.21875                (Uni-Lions 2nd)    7.0
7   0.15625                    (Fubon 2nd)    5.0
4   0.12500                  (Dragons 1st)    4.0
19  0.12500    (Brothers 2nd, Rakuten 1st)    4.0
2   0.09375                    (Fubon 1st)    3.0
23  0.09375  (Uni-Lions 2nd, Brothers 1st)    3.0
18  0.09375   (Uni-Lions 2nd, Rakuten 1st)    3.0
16  0.09375  (Brothers 2nd, Uni-Lions 1st)    3.0
24  0.06250      (Brothers 1st, Fubon 2nd)    2.0
17  0.06250   (Dragons 2nd, Uni-Lions 1st)    2.0
15  0.06250     (Fubon 2nd, Uni-Lions 1st)    2.0
14  0.06250   (Rakuten 2nd, Uni-Lions 1st)    2.0
10  0.06250                    (Whale 2nd)    2.0
9   0.06250                  (Dragons 2nd)    2.0
6   0.06250                  (Rakuten 2nd)    2.0
13  0.03125                    (T-REX 2nd)    1.0
12  0.03125                     (Hank 2nd)    1.0
11  0.03125                    (Tiger 2nd)    1.0
20  0.03125     (Uni-Lions 2nd, Fubon 1st)    1.0
21  0.03125      (Fubon 1st, Brothers 2nd)    1.0
22  0.03125         (Fubon 1st, T-REX 2nd)    1.0
25  0.03125      (Brothers 1st, Whale 2nd)    1.0
26  0.03125       (Dragons 1st, Fubon 2nd)    1.0
27  0.03125       (Dragons 1st, Whale 2nd)    1.0
28  0.03125       (Tiger 2nd, Dragons 1st)    1.0
29  0.03125        (Dragons 1st, Hank 2nd)    1.0

In [4]:
def table1query(table, query1, query2=None):
    
    if query2 is None:
        print('Now query : ' + query1 )
        temp = table[table[query1]]
        print(temp.index)
    else:
        print('Now query : '+ query1 + ' + '+ query2 )
        temp = table[table[query1] & table[query2]]
        print(temp.index)
    print()

In [5]:
# Part1 Table Query
table1query(part1, 'Uni-Lions 1st')
table1query(part1, 'Brothers 1st')
table1query(part1, 'Rakuten 1st')
table1query(part1, 'Dragons 1st')
table1query(part1, 'Fubon 1st')

table1query(part1, 'Brothers 2nd')
table1query(part1, 'Uni-Lions 2nd')
table1query(part1, 'Fubon 2nd')
table1query(part1, 'Whale 2nd')
table1query(part1, 'Dragons 2nd')
table1query(part1, 'Rakuten 2nd')
table1query(part1, 'T-REX 2nd')
table1query(part1, 'Hank 2nd')
table1query(part1, 'Tiger 2nd')

table1query(part1, 'Rakuten 1st', 'Brothers 2nd')
table1query(part1, 'Brothers 1st', 'Uni-Lions 2nd')
table1query(part1, 'Rakuten 1st', 'Uni-Lions 2nd')
table1query(part1, 'Uni-Lions 1st', 'Brothers 2nd')
table1query(part1, 'Brothers 1st', 'Fubon 2nd')
table1query(part1, 'Uni-Lions 1st', 'Dragons 2nd')
table1query(part1, 'Uni-Lions 1st', 'Fubon 2nd')
table1query(part1, 'Uni-Lions 1st', 'Rakuten 2nd')
table1query(part1, 'Fubon 1st', 'Uni-Lions 2nd')
table1query(part1, 'Fubon 1st', 'Brothers 2nd')
table1query(part1, 'Fubon 1st', 'T-REX 2nd')
table1query(part1, 'Brothers 1st', 'Whale 2nd')
table1query(part1, 'Dragons 1st', 'Fubon 2nd')
table1query(part1, 'Dragons 1st', 'Whale 2nd')
table1query(part1, 'Dragons 1st', 'Tiger 2nd')
table1query(part1, 'Dragons 1st', 'Hank 2nd')

Now query : Uni-Lions 1st
Int64Index([1991, 1995, 1996, 2000, 2007, 2008, 2009, 2011, 2013, 2020], dtype='int64', name='職棒年')

Now query : Brothers 1st
Int64Index([1992, 1993, 1994, 2001, 2002, 2003, 2010, 2021], dtype='int64', name='職棒年')

Now query : Rakuten 1st
Int64Index([2006, 2012, 2014, 2015, 2017, 2018, 2019], dtype='int64', name='職棒年')

Now query : Dragons 1st
Int64Index([1990, 1997, 1998, 1999], dtype='int64', name='職棒年')

Now query : Fubon 1st
Int64Index([2004, 2005, 2016], dtype='int64', name='職棒年')

Now query : Brothers 2nd
Int64Index([2008, 2009, 2014, 2015, 2016, 2017, 2019, 2020], dtype='int64', name='職棒年')

Now query : Uni-Lions 2nd
Int64Index([1993, 2001, 2004, 2006, 2012, 2018, 2021], dtype='int64', name='職棒年')

Now query : Fubon 2nd
Int64Index([1998, 2000, 2003, 2010, 2013], dtype='int64', name='職棒年')

Now query : Whale 2nd
Int64Index([1999, 2002], dtype='int64', name='職棒年')

Now query : Dragons 2nd
Int64Index([1991, 1996], dtype='int64', name='職棒年')

Now query : Rakuten 2nd
Int64Index([2007, 2011], dtype='int64', name='職棒年')

Now query : T-REX 2nd
Int64Index([2005], dtype='int64', name='職棒年')

Now query : Hank 2nd
Int64Index([1997], dtype='int64', name='職棒年')

Now query : Tiger 2nd
Int64Index([1990], dtype='int64', name='職棒年')

Now query : Rakuten 1st + Brothers 2nd
Int64Index([2014, 2015, 2017, 2019], dtype='int64', name='職棒年')

Now query : Brothers 1st + Uni-Lions 2nd
Int64Index([1993, 2001, 2021], dtype='int64', name='職棒年')

Now query : Rakuten 1st + Uni-Lions 2nd
Int64Index([2006, 2012, 2018], dtype='int64', name='職棒年')

Now query : Uni-Lions 1st + Brothers 2nd
Int64Index([2008, 2009, 2020], dtype='int64', name='職棒年')

Now query : Brothers 1st + Fubon 2nd
Int64Index([2003, 2010], dtype='int64', name='職棒年')

Now query : Uni-Lions 1st + Dragons 2nd
Int64Index([1991, 1996], dtype='int64', name='職棒年')

Now query : Uni-Lions 1st + Fubon 2nd
Int64Index([2000, 2013], dtype='int64', name='職棒年')

Now query : Uni-Lions 1st + Rakuten 2nd
Int64Index([2007, 2011], dtype='int64', name='職棒年')

Now query : Fubon 1st + Uni-Lions 2nd
Int64Index([2004], dtype='int64', name='職棒年')

Now query : Fubon 1st + Brothers 2nd
Int64Index([2016], dtype='int64', name='職棒年')

Now query : Fubon 1st + T-REX 2nd
Int64Index([2005], dtype='int64', name='職棒年')

Now query : Brothers 1st + Whale 2nd
Int64Index([2002], dtype='int64', name='職棒年')

Now query : Dragons 1st + Fubon 2nd
Int64Index([1998], dtype='int64', name='職棒年')

Now query : Dragons 1st + Whale 2nd
Int64Index([1999], dtype='int64', name='職棒年')

Now query : Dragons 1st + Tiger 2nd
Int64Index([1990], dtype='int64', name='職棒年')

Now query : Dragons 1st + Hank 2nd
Int64Index([1997], dtype='int64', name='職棒年')

In [6]:
# Part1 : 對戰組合Mining (Last 10 Years)
min_support = 0.1

frequent_1_tail10 = apriori(part1.tail(10), min_support=min_support, use_colnames=True)
frequent_1_tail10 = frequent_1_tail10.sort_values('support', ascending=False)
frequent_1_tail10['total'] = frequent_1_tail10['support'] / 0.1
frequent_1_tail10

    support                       itemsets  total
1       0.6                  (Rakuten 1st)    6.0
6       0.6                 (Brothers 2nd)    6.0
10      0.4    (Brothers 2nd, Rakuten 1st)    4.0
4       0.3                (Uni-Lions 2nd)    3.0
0       0.2                (Uni-Lions 1st)    2.0
9       0.2   (Uni-Lions 2nd, Rakuten 1st)    2.0
2       0.1                    (Fubon 1st)    1.0
3       0.1                 (Brothers 1st)    1.0
5       0.1                    (Fubon 2nd)    1.0
7       0.1     (Fubon 2nd, Uni-Lions 1st)    1.0
8       0.1  (Brothers 2nd, Uni-Lions 1st)    1.0
11      0.1      (Fubon 1st, Brothers 2nd)    1.0
12      0.1  (Uni-Lions 2nd, Brothers 1st)    1.0

In [7]:
# Part1 Table Query
table1query(part1.tail(10), 'Rakuten 1st')
table1query(part1.tail(10), 'Uni-Lions 1st')
table1query(part1.tail(10), 'Fubon 1st')
table1query(part1.tail(10), 'Brothers 1st')

table1query(part1.tail(10), 'Brothers 2nd')
table1query(part1.tail(10), 'Uni-Lions 2nd')
table1query(part1.tail(10), 'Fubon 2nd')

table1query(part1.tail(10), 'Rakuten 1st', 'Brothers 2nd')
table1query(part1.tail(10), 'Rakuten 1st', 'Uni-Lions 2nd')
table1query(part1.tail(10), 'Uni-Lions 1st', 'Fubon 2nd')
table1query(part1.tail(10), 'Uni-Lions 1st', 'Brothers 2nd')
table1query(part1.tail(10), 'Fubon 1st', 'Brothers 2nd')
table1query(part1.tail(10), 'Brothers 1st', 'Uni-Lions 2nd')

Now query : Rakuten 1st
Int64Index([2012, 2014, 2015, 2017, 2018, 2019], dtype='int64', name='職棒年')

Now query : Uni-Lions 1st
Int64Index([2013, 2020], dtype='int64', name='職棒年')

Now query : Fubon 1st
Int64Index([2016], dtype='int64', name='職棒年')

Now query : Brothers 1st
Int64Index([2021], dtype='int64', name='職棒年')

Now query : Brothers 2nd
Int64Index([2014, 2015, 2016, 2017, 2019, 2020], dtype='int64', name='職棒年')

Now query : Uni-Lions 2nd
Int64Index([2012, 2018, 2021], dtype='int64', name='職棒年')

Now query : Fubon 2nd
Int64Index([2013], dtype='int64', name='職棒年')

Now query : Rakuten 1st + Brothers 2nd
Int64Index([2014, 2015, 2017, 2019], dtype='int64', name='職棒年')

Now query : Rakuten 1st + Uni-Lions 2nd
Int64Index([2012, 2018], dtype='int64', name='職棒年')

Now query : Uni-Lions 1st + Fubon 2nd
Int64Index([2013], dtype='int64', name='職棒年')

Now query : Uni-Lions 1st + Brothers 2nd
Int64Index([2020], dtype='int64', name='職棒年')

Now query : Fubon 1st + Brothers 2nd
Int64Index([2016], dtype='int64', name='職棒年')

Now query : Brothers 1st + Uni-Lions 2nd
Int64Index([2021], dtype='int64', name='職棒年')

In [8]:
################################################################################################################################

In [9]:
################################################################################################################################

In [10]:
################################################################################################################################

In [11]:
################################################################################################################################

In [12]:
################################################################################################################################

In [13]:
#Part2: 進階屬性Mining
part2 = raw_data_cpbl_s1[['G1W', 'G2W', 'G3W', 'G4W', 'G5W', 'G6W', 'G7W',
                       'G1L', 'G2L', 'G3L', 'G4L', 'G5L', 'G6L', 'G7L',
                       'F.H.C', 'S.H.C','A.S.C',
                       'Pitcher_W', 'Pitcher_SO', 'Pitcher_ERA', 'Pitcher_SV', 'Pitcher_H',   
                       'Batter_H',  'Batter_AVG', 'Batter_RBI',  'Batter_SB',  'Batter_HR',
                       'MVP_Pitcher', 'MVP_Batter'
                      ]]


frequent_2 = apriori(part2, min_support=0.3, use_colnames=True)
frequent_2 = frequent_2.sort_values('support', ascending=False)
frequent_2

     support                       itemsets
0   0.862069                          (G1W)
3   0.724138                          (G4W)
17  0.689655                   (MVP_Batter)
32  0.620690              (G1W, MVP_Batter)
2   0.586207                          (G3W)
..       ...                            ...
52  0.310345            (F.H.C, MVP_Batter)
53  0.310345                 (S.H.C, A.S.C)
57  0.310345              (G1W, G2W, A.S.C)
60  0.310345              (G1W, S.H.C, G3W)
85  0.310345  (S.H.C, G3W, G4W, MVP_Batter)

[86 rows x 2 columns]

In [14]:
def table2query(table, query1, query2=None, special=None, b_all=None):
    print('Now query : ' + query1 , end = ', \t\t')
    
    a = len(table[table[query1]])
    
    if special is not None:
        b = len(table[table[query2] | table[special]])
    elif b_all is not None:
        b = len(table)
    else:
        b = len(table[table[query2]])

    print('Rate is : '+ str(a/b))

In [15]:
# Part2 Table Query
table2query(part2, query1='G1W', query2='G1W', special='G1L')
table2query(part2, query1='G2W', query2='G2W', special='G2L')
table2query(part2, query1='G3W', query2='G3W', special='G3L')
table2query(part2, query1='G4W', query2='G4W', special='G4L')
table2query(part2, query1='G5W', query2='G5W', special='G5L')
table2query(part2, query1='G6W', query2='G6W', special='G6L')
table2query(part2, query1='G7W', query2='G7W', special='G7L')
table2query(part2, query1='G1L', query2='G1W', special='G1L')
table2query(part2, query1='G2L', query2='G2W', special='G2L')
table2query(part2, query1='G3L', query2='G3W', special='G3L')
table2query(part2, query1='G4L', query2='G4W', special='G4L')
table2query(part2, query1='G5L', query2='G5W', special='G5L')
table2query(part2, query1='G6L', query2='G6W', special='G6L')
table2query(part2, query1='G7L', query2='G7W', special='G7L')

table2query(part2, query1='F.H.C', b_all=True)
table2query(part2, query1='S.H.C', b_all=True)
table2query(part2, query1='A.S.C', b_all=True)

table2query(part2, query1='Pitcher_W', b_all=True)
table2query(part2, query1='Pitcher_SO', b_all=True)
table2query(part2, query1='Pitcher_ERA', b_all=True)
table2query(part2, query1='Pitcher_SV', b_all=True)
table2query(part2, query1='Pitcher_H', b_all=True)
table2query(part2, query1='Batter_H', b_all=True)
table2query(part2, query1='Batter_AVG', b_all=True)
table2query(part2, query1='Batter_RBI', b_all=True)
table2query(part2, query1='Batter_SB', b_all=True)
table2query(part2, query1='Batter_HR', b_all=True)

table2query(part2, query1='MVP_Pitcher', b_all=True)
table2query(part2, query1='MVP_Batter', b_all=True)

Now query : G1W, 		Rate is : 0.8620689655172413
Now query : G2W, 		Rate is : 0.5862068965517241
Now query : G3W, 		Rate is : 0.5862068965517241
Now query : G4W, 		Rate is : 0.7241379310344828
Now query : G5W, 		Rate is : 0.6086956521739131
Now query : G6W, 		Rate is : 0.7058823529411765
Now query : G7W, 		Rate is : 1.0
Now query : G1L, 		Rate is : 0.13793103448275862
Now query : G2L, 		Rate is : 0.41379310344827586
Now query : G3L, 		Rate is : 0.41379310344827586
Now query : G4L, 		Rate is : 0.27586206896551724
Now query : G5L, 		Rate is : 0.391304347826087
Now query : G6L, 		Rate is : 0.29411764705882354
Now query : G7L, 		Rate is : 0.0
Now query : F.H.C, 		Rate is : 0.4482758620689655
Now query : S.H.C, 		Rate is : 0.5862068965517241
Now query : A.S.C, 		Rate is : 0.5517241379310345
Now query : Pitcher_W, 		Rate is : 0.27586206896551724
Now query : Pitcher_SO, 		Rate is : 0.1724137931034483
Now query : Pitcher_ERA, 		Rate is : 0.27586206896551724
Now query : Pitcher_SV, 		Rate is : 0.3793103448275862
Now query : Pitcher_H, 		Rate is : 0.20689655172413793
Now query : Batter_H, 		Rate is : 0.2413793103448276
Now query : Batter_AVG, 		Rate is : 0.2413793103448276
Now query : Batter_RBI, 		Rate is : 0.3448275862068966
Now query : Batter_SB, 		Rate is : 0.3448275862068966
Now query : Batter_HR, 		Rate is : 0.2413793103448276
Now query : MVP_Pitcher, 		Rate is : 0.3103448275862069
Now query : MVP_Batter, 		Rate is : 0.6896551724137931

In [16]:
#Part2: 進階屬性Mining(Last 10 Years)
frequent_2_TAIL10 = apriori(part2.tail(10), min_support=0.5, use_colnames=True)
frequent_2_TAIL10 = frequent_2_TAIL10.sort_values('support', ascending=False)
frequent_2_TAIL10

    support                         itemsets
9       1.0                     (MVP_Batter)
0       0.9                            (G1W)
17      0.9                (G1W, MVP_Batter)
4       0.8                            (G5W)
25      0.8                (G5W, MVP_Batter)
35      0.7           (G1W, G5W, MVP_Batter)
13      0.7                       (G1W, G5W)
30      0.6              (MVP_Batter, A.S.C)
29      0.6              (S.H.C, MVP_Batter)
28      0.6              (F.H.C, MVP_Batter)
37      0.6         (G1W, F.H.C, MVP_Batter)
21      0.6                (G4W, MVP_Batter)
20      0.6                (G3W, MVP_Batter)
39      0.6         (G1W, MVP_Batter, A.S.C)
16      0.6                     (G1W, A.S.C)
8       0.6                          (A.S.C)
14      0.6                     (G1W, F.H.C)
2       0.6                            (G3W)
3       0.6                            (G4W)
6       0.6                          (F.H.C)
7       0.6                          (S.H.C)
36      0.5              (G1W, F.H.C, A.S.C)
45      0.5    (G1W, G5W, F.H.C, MVP_Batter)
34      0.5                (G1W, G5W, F.H.C)
41      0.5           (G5W, G2L, MVP_Batter)
32      0.5           (G1W, G3W, MVP_Batter)
38      0.5         (G1W, S.H.C, MVP_Batter)
44      0.5       (F.H.C, MVP_Batter, A.S.C)
43      0.5         (G5W, S.H.C, MVP_Batter)
42      0.5         (F.H.C, G5W, MVP_Batter)
40      0.5           (G3W, G4W, MVP_Batter)
33      0.5           (G1W, G4W, MVP_Batter)
23      0.5                     (G5W, F.H.C)
31      0.5           (G1W, G2W, MVP_Batter)
27      0.5                   (F.H.C, A.S.C)
26      0.5                (G2L, MVP_Batter)
24      0.5                     (G5W, S.H.C)
1       0.5                            (G2W)
22      0.5                       (G5W, G2L)
19      0.5                       (G3W, G4W)
18      0.5                (G2W, MVP_Batter)
15      0.5                     (G1W, S.H.C)
12      0.5                       (G1W, G4W)
11      0.5                       (G1W, G3W)
10      0.5                       (G1W, G2W)
5       0.5                            (G2L)
46      0.5  (G1W, MVP_Batter, F.H.C, A.S.C)

In [17]:
# Part2 Table Query
table2query(part2.tail(10), query1='G1W', query2='G1W', special='G1L')
table2query(part2.tail(10), query1='G2W', query2='G2W', special='G2L')
table2query(part2.tail(10), query1='G3W', query2='G3W', special='G3L')
table2query(part2.tail(10), query1='G4W', query2='G4W', special='G4L')
table2query(part2.tail(10), query1='G5W', query2='G5W', special='G5L')
table2query(part2.tail(10), query1='G6W', query2='G6W', special='G6L')
table2query(part2.tail(10), query1='G7W', query2='G7W', special='G7L')
table2query(part2.tail(10), query1='G1L', query2='G1W', special='G1L')
table2query(part2.tail(10), query1='G2L', query2='G2W', special='G2L')
table2query(part2.tail(10), query1='G3L', query2='G3W', special='G3L')
table2query(part2.tail(10), query1='G4L', query2='G4W', special='G4L')
table2query(part2.tail(10), query1='G5L', query2='G5W', special='G5L')
table2query(part2.tail(10), query1='G6L', query2='G6W', special='G6L')
table2query(part2.tail(10), query1='G7L', query2='G7W', special='G7L')

table2query(part2.tail(10), query1='F.H.C', b_all=True)
table2query(part2.tail(10), query1='S.H.C', b_all=True)
table2query(part2.tail(10), query1='A.S.C', b_all=True)

table2query(part2.tail(10), query1='Pitcher_W', b_all=True)
table2query(part2.tail(10), query1='Pitcher_SO', b_all=True)
table2query(part2.tail(10), query1='Pitcher_ERA', b_all=True)
table2query(part2.tail(10), query1='Pitcher_SV', b_all=True)
table2query(part2.tail(10), query1='Pitcher_H', b_all=True)
table2query(part2.tail(10), query1='Batter_H', b_all=True)
table2query(part2.tail(10), query1='Batter_AVG', b_all=True)
table2query(part2.tail(10), query1='Batter_RBI', b_all=True)
table2query(part2.tail(10), query1='Batter_SB', b_all=True)
table2query(part2.tail(10), query1='Batter_HR', b_all=True)

table2query(part2.tail(10), query1='MVP_Pitcher', b_all=True)
table2query(part2.tail(10), query1='MVP_Batter', b_all=True)

Now query : G1W, 		Rate is : 0.9
Now query : G2W, 		Rate is : 0.5
Now query : G3W, 		Rate is : 0.6
Now query : G4W, 		Rate is : 0.6
Now query : G5W, 		Rate is : 1.0
Now query : G6W, 		Rate is : 1.0
Now query : G7W, 		Rate is : 1.0
Now query : G1L, 		Rate is : 0.1
Now query : G2L, 		Rate is : 0.5
Now query : G3L, 		Rate is : 0.4
Now query : G4L, 		Rate is : 0.4
Now query : G5L, 		Rate is : 0.0
Now query : G6L, 		Rate is : 0.0
Now query : G7L, 		Rate is : 0.0
Now query : F.H.C, 		Rate is : 0.6
Now query : S.H.C, 		Rate is : 0.6
Now query : A.S.C, 		Rate is : 0.6
Now query : Pitcher_W, 		Rate is : 0.2
Now query : Pitcher_SO, 		Rate is : 0.3
Now query : Pitcher_ERA, 		Rate is : 0.2
Now query : Pitcher_SV, 		Rate is : 0.4
Now query : Pitcher_H, 		Rate is : 0.4
Now query : Batter_H, 		Rate is : 0.4
Now query : Batter_AVG, 		Rate is : 0.4
Now query : Batter_RBI, 		Rate is : 0.3
Now query : Batter_SB, 		Rate is : 0.3
Now query : Batter_HR, 		Rate is : 0.4
Now query : MVP_Pitcher, 		Rate is : 0.0
Now query : MVP_Batter, 		Rate is : 1.0

In [18]:
################################################################################################################################

In [19]:
################################################################################################################################

In [20]:
################################################################################################################################

In [21]:
################################################################################################################################

In [22]:
################################################################################################################################

In [23]:
#Part3: 球隊贏球風格 (Uni-Lions)
frequent_UNILIONS = raw_data_cpbl_s1[raw_data_cpbl_s1['Uni-Lions 1st']]

frequent_UNILIONS = apriori(frequent_UNILIONS, min_support=0.5, use_colnames=True)
frequent_UNILIONS = frequent_UNILIONS.sort_values('support', ascending=False)
frequent_UNILIONS

     support                           itemsets
8   1.000000                    (Uni-Lions 1st)
20  0.888889               (G4W, Uni-Lions 1st)
2   0.888889                              (G4W)
0   0.777778                              (G1W)
10  0.777778               (G1W, Uni-Lions 1st)
28  0.666667          (G1W, G4W, Uni-Lions 1st)
23  0.666667               (G7W, Uni-Lions 1st)
18  0.666667                       (G4W, A.S.C)
24  0.666667               (G3L, Uni-Lions 1st)
38  0.666667        (Uni-Lions 1st, G4W, A.S.C)
31  0.666667          (G2W, G4W, Uni-Lions 1st)
14  0.666667               (G2W, Uni-Lions 1st)
4   0.666667                              (G3L)
11  0.666667                         (G2W, G4W)
1   0.666667                              (G2W)
9   0.666667                         (G1W, G4W)
3   0.666667                              (G7W)
6   0.666667                            (A.S.C)
26  0.666667             (Uni-Lions 1st, A.S.C)
34  0.555556                    (G6L, G4W, G7W)
33  0.555556        (G2W, Uni-Lions 1st, A.S.C)
39  0.555556  (Uni-Lions 1st, MVP_Pitcher, G4W)
35  0.555556          (G7W, G4W, Uni-Lions 1st)
36  0.555556          (G3L, G4W, Uni-Lions 1st)
37  0.555556          (G6L, G4W, Uni-Lions 1st)
40  0.555556          (G7W, G3L, Uni-Lions 1st)
41  0.555556          (G6L, G7W, Uni-Lions 1st)
42  0.555556     (G2W, G3L, G4W, Uni-Lions 1st)
43  0.555556   (G2W, Uni-Lions 1st, G4W, A.S.C)
32  0.555556          (G2W, G3L, Uni-Lions 1st)
22  0.555556                         (G6L, G7W)
30  0.555556                  (G2W, G4W, A.S.C)
29  0.555556                    (G2W, G3L, G4W)
27  0.555556       (MVP_Pitcher, Uni-Lions 1st)
25  0.555556               (G6L, Uni-Lions 1st)
21  0.555556                         (G3L, G7W)
19  0.555556                 (MVP_Pitcher, G4W)
17  0.555556                         (G6L, G4W)
16  0.555556                         (G3L, G4W)
15  0.555556                         (G4W, G7W)
13  0.555556                       (G2W, A.S.C)
12  0.555556                         (G2W, G3L)
7   0.555556                      (MVP_Pitcher)
5   0.555556                              (G6L)
44  0.555556     (G6L, G7W, G4W, Uni-Lions 1st)

In [24]:
#Part3: 球隊贏球風格 (Rakuten)
frequent_Rakuten = raw_data_cpbl_s1[raw_data_cpbl_s1['Rakuten 1st']]

frequent_Rakuten = apriori(frequent_Rakuten, min_support=0.6, use_colnames=True)
frequent_Rakuten = frequent_Rakuten.sort_values('support', ascending=False)
frequent_Rakuten

     support                                      itemsets
0   1.000000                                         (G1W)
28  1.000000                (G1W, Rakuten 1st, MVP_Batter)
4   1.000000                                  (MVP_Batter)
5   1.000000                                 (Rakuten 1st)
9   1.000000                             (G1W, MVP_Batter)
10  1.000000                            (G1W, Rakuten 1st)
19  1.000000                     (Rakuten 1st, MVP_Batter)
41  0.857143         (G1W, Rakuten 1st, F.H.C, MVP_Batter)
31  0.857143                (G5W, Rakuten 1st, MVP_Batter)
38  0.857143           (G1W, G5W, Rakuten 1st, MVP_Batter)
25  0.857143                     (G1W, Rakuten 1st, F.H.C)
24  0.857143                      (G1W, F.H.C, MVP_Batter)
1   0.857143                                         (G5W)
22  0.857143                       (G1W, G5W, Rakuten 1st)
21  0.857143                        (G1W, G5W, MVP_Batter)
16  0.857143                          (Rakuten 1st, F.H.C)
34  0.857143              (F.H.C, Rakuten 1st, MVP_Batter)
2   0.857143                                       (F.H.C)
13  0.857143                            (G5W, Rakuten 1st)
12  0.857143                             (G5W, MVP_Batter)
15  0.857143                           (F.H.C, MVP_Batter)
7   0.857143                                  (G1W, F.H.C)
6   0.857143                                    (G1W, G5W)
37  0.714286                (G1W, G5W, Rakuten 1st, F.H.C)
35  0.714286              (MVP_Batter, Rakuten 1st, A.S.C)
36  0.714286                 (G1W, G5W, F.H.C, MVP_Batter)
45  0.714286    (F.H.C, Rakuten 1st, G1W, G5W, MVP_Batter)
33  0.714286                   (F.H.C, Rakuten 1st, A.S.C)
43  0.714286         (F.H.C, G5W, Rakuten 1st, MVP_Batter)
39  0.714286               (G1W, MVP_Batter, F.H.C, A.S.C)
42  0.714286         (G1W, MVP_Batter, Rakuten 1st, A.S.C)
40  0.714286              (G1W, Rakuten 1st, F.H.C, A.S.C)
44  0.714286       (F.H.C, MVP_Batter, Rakuten 1st, A.S.C)
23  0.714286                           (G1W, F.H.C, A.S.C)
32  0.714286                    (F.H.C, MVP_Batter, A.S.C)
30  0.714286                     (G5W, Rakuten 1st, F.H.C)
29  0.714286                      (F.H.C, G5W, MVP_Batter)
27  0.714286                     (G1W, Rakuten 1st, A.S.C)
26  0.714286                      (G1W, MVP_Batter, A.S.C)
20  0.714286                             (G1W, G5W, F.H.C)
18  0.714286                          (Rakuten 1st, A.S.C)
17  0.714286                           (MVP_Batter, A.S.C)
14  0.714286                                (F.H.C, A.S.C)
11  0.714286                                  (G5W, F.H.C)
8   0.714286                                  (G1W, A.S.C)
3   0.714286                                       (A.S.C)
46  0.714286  (F.H.C, Rakuten 1st, G1W, A.S.C, MVP_Batter)

In [25]:
#Part3: 球隊贏球風格 (Fubon)
frequent_Fubon = raw_data_cpbl_s1[raw_data_cpbl_s1['Fubon 1st']]

frequent_Fubon = apriori(frequent_Fubon, min_support=0.66, use_colnames=True)
frequent_Fubon = frequent_Fubon.sort_values('support', ascending=False)
frequent_Fubon[:50]

     support                                        itemsets
5   1.000000                                         (S.H.C)
30  1.000000                              (Fubon 1st, S.H.C)
9   1.000000                                     (Fubon 1st)
0   0.666667                                           (G1W)
56  0.666667                         (Fubon 1st, S.H.C, G6W)
63  0.666667                    (Fubon 1st, G1W, S.H.C, G2W)
62  0.666667              (Fubon 1st, Pitcher_W, MVP_Batter)
61  0.666667                  (Fubon 1st, S.H.C, MVP_Batter)
60  0.666667                   (Batter_HR, S.H.C, Fubon 1st)
59  0.666667                   (Fubon 1st, Pitcher_W, S.H.C)
58  0.666667                  (Pitcher_W, S.H.C, MVP_Batter)
57  0.666667                     (Batter_HR, G6W, Fubon 1st)
54  0.666667                    (Fubon 1st, G4W, MVP_Batter)
55  0.666667                         (Batter_HR, S.H.C, G6W)
65  0.666667                   (S.H.C, G3W, G4W, MVP_Batter)
53  0.666667                     (Fubon 1st, Pitcher_W, G4W)
52  0.666667                    (Pitcher_W, G4W, MVP_Batter)
51  0.666667                         (Fubon 1st, S.H.C, G4W)
50  0.666667                        (S.H.C, G4W, MVP_Batter)
49  0.666667                         (Pitcher_W, S.H.C, G4W)
48  0.666667                    (Fubon 1st, G3W, MVP_Batter)
47  0.666667                     (Fubon 1st, Pitcher_W, G3W)
64  0.666667                    (Pitcher_W, G3W, S.H.C, G4W)
67  0.666667               (Pitcher_W, G3W, G4W, MVP_Batter)
66  0.666667                    (Fubon 1st, S.H.C, G3W, G4W)
77  0.666667         (Fubon 1st, Pitcher_W, G4W, MVP_Batter)
85  0.666667  (G4W, Fubon 1st, Pitcher_W, S.H.C, MVP_Batter)
84  0.666667  (G3W, Fubon 1st, Pitcher_W, S.H.C, MVP_Batter)
83  0.666667    (G3W, G4W, Fubon 1st, Pitcher_W, MVP_Batter)
82  0.666667        (G3W, G4W, Fubon 1st, S.H.C, MVP_Batter)
81  0.666667         (G3W, G4W, Fubon 1st, Pitcher_W, S.H.C)
80  0.666667        (G3W, G4W, Pitcher_W, S.H.C, MVP_Batter)
79  0.666667       (Fubon 1st, Pitcher_W, S.H.C, MVP_Batter)
78  0.666667              (Batter_HR, S.H.C, G6W, Fubon 1st)
76  0.666667             (Fubon 1st, S.H.C, G4W, MVP_Batter)
45  0.666667                         (Fubon 1st, S.H.C, G3W)
75  0.666667              (Fubon 1st, Pitcher_W, S.H.C, G4W)
74  0.666667             (Pitcher_W, S.H.C, G4W, MVP_Batter)
73  0.666667         (Fubon 1st, Pitcher_W, G3W, MVP_Batter)
72  0.666667             (Fubon 1st, S.H.C, G3W, MVP_Batter)
71  0.666667              (Fubon 1st, Pitcher_W, G3W, S.H.C)
70  0.666667             (Pitcher_W, G3W, S.H.C, MVP_Batter)
69  0.666667               (Fubon 1st, G3W, G4W, MVP_Batter)
68  0.666667                (Fubon 1st, Pitcher_W, G3W, G4W)
46  0.666667                    (Pitcher_W, G3W, MVP_Batter)
43  0.666667                         (Pitcher_W, G3W, S.H.C)
44  0.666667                        (S.H.C, G3W, MVP_Batter)
22  0.666667                               (G4W, MVP_Batter)
20  0.666667                                    (S.H.C, G4W)
19  0.666667                                (Fubon 1st, G3W)

In [26]:
#Part3: 球隊贏球風格 (Brothers)
frequent_Brothers = raw_data_cpbl_s1[raw_data_cpbl_s1['Brothers 1st']]

frequent_Brothers = apriori(frequent_Brothers, min_support=0.5, use_colnames=True)
frequent_Brothers = frequent_Brothers.sort_values('support', ascending=False)
frequent_Brothers[:50]

      support                              itemsets
0    1.000000                                 (G1W)
23   1.000000                   (G1W, Brothers 1st)
11   1.000000                        (Brothers 1st)
3    0.833333                                 (G4W)
39   0.833333                   (Brothers 1st, G4W)
65   0.833333              (G1W, Brothers 1st, G4W)
15   0.833333                            (G1W, G4W)
1    0.666667                                 (G2W)
29   0.666667                   (G2W, Brothers 1st)
30   0.666667                            (G3W, G4W)
75   0.666667       (G1W, Brothers 1st, MVP_Batter)
34   0.666667                   (Brothers 1st, G3W)
38   0.666667                     (G4W, MVP_Batter)
69   0.666667            (G1W, S.H.C, Brothers 1st)
60   0.666667              (G1W, Brothers 1st, G3W)
113  0.666667         (G1W, Brothers 1st, G3W, G4W)
55   0.666667              (G1W, Brothers 1st, G2W)
43   0.666667                 (S.H.C, Brothers 1st)
64   0.666667                (G1W, G4W, MVP_Batter)
49   0.666667            (Brothers 1st, MVP_Batter)
123  0.666667  (G1W, Brothers 1st, G4W, MVP_Batter)
52   0.666667                       (G1W, G2W, G4W)
26   0.666667                            (G2W, G4W)
106  0.666667         (G1W, Brothers 1st, G2W, G4W)
13   0.666667                            (G1W, G2W)
14   0.666667                            (G1W, G3W)
2    0.666667                                 (G3W)
6    0.666667                               (S.H.C)
88   0.666667              (Brothers 1st, G3W, G4W)
98   0.666667       (Brothers 1st, G4W, MVP_Batter)
10   0.666667                          (MVP_Batter)
56   0.666667                       (G1W, G3W, G4W)
81   0.666667              (G2W, Brothers 1st, G4W)
22   0.666667                     (G1W, MVP_Batter)
18   0.666667                          (G1W, S.H.C)
107  0.500000         (G1W, G2W, F.H.C, MVP_Batter)
118  0.500000         (G1W, G4W, F.H.C, MVP_Batter)
95   0.500000            (S.H.C, Brothers 1st, G4W)
96   0.500000              (MVP_Batter, G4W, A.S.C)
103  0.500000         (G1W, Brothers 1st, G3W, G2W)
117  0.500000  (G1W, Brothers 1st, G3W, MVP_Batter)
119  0.500000       (G1W, Brothers 1st, G4W, F.H.C)
116  0.500000       (G1W, Brothers 1st, G3W, A.S.C)
115  0.500000         (G1W, G3W, MVP_Batter, A.S.C)
97   0.500000            (Brothers 1st, G4W, A.S.C)
114  0.500000       (G1W, Brothers 1st, G3W, S.H.C)
108  0.500000       (G1W, Brothers 1st, G2W, F.H.C)
102  0.500000                  (G1W, G3W, G2W, G4W)
99   0.500000     (F.H.C, Brothers 1st, MVP_Batter)
112  0.500000           (G1W, G3W, G4W, MVP_Batter)

In [27]:
#Part3: 球隊贏球風格 (Dragons)
frequent_Dragons = raw_data_cpbl_s1[raw_data_cpbl_s1['Dragons 1st']]
frequent_Dragons = apriori(frequent_Dragons, min_support=0.5, use_colnames=True)
frequent_Dragons = frequent_Dragons.sort_values('support', ascending=False)
frequent_Dragons[:50]

     support                                  itemsets
33      1.00                        (Dragons 1st, G3W)
13      1.00                             (Dragons 1st)
1       1.00                                     (G3W)
0       0.75                                     (G1W)
53      0.75                          (Batter_SB, G2L)
32      0.75                         (G3W, MVP_Batter)
261     0.75        (Batter_SB, Dragons 1st, G3W, G6W)
178     0.75             (Batter_SB, Dragons 1st, G2L)
41      0.75                                (G2L, G6W)
131     0.75            (Dragons 1st, G3W, MVP_Batter)
94      0.75            (G1W, Dragons 1st, MVP_Batter)
130     0.75             (Batter_SB, Dragons 1st, G3W)
48      0.75                        (Dragons 1st, G6W)
317     0.75        (Batter_SB, Dragons 1st, G2L, G6W)
249     0.75              (Dragons 1st, G3W, G2L, G6W)
55      0.75                        (Dragons 1st, G2L)
247     0.75                (Batter_SB, G3W, G2L, G6W)
116     0.75                   (Dragons 1st, G3W, G2L)
69      0.75                  (Batter_SB, Dragons 1st)
70      0.75                 (Dragons 1st, MVP_Batter)
114     0.75                     (Batter_SB, G3W, G2L)
76      0.75                    (G1W, G3W, MVP_Batter)
77      0.75                   (G1W, Dragons 1st, G3W)
109     0.75                   (Dragons 1st, G3W, G6W)
107     0.75                     (Batter_SB, G3W, G6W)
206     0.75       (G1W, Dragons 1st, G3W, MVP_Batter)
102     0.75                           (G3W, G2L, G6W)
31      0.75                          (Batter_SB, G3W)
46      0.75                          (Batter_SB, G6W)
274     0.75        (Batter_SB, Dragons 1st, G3W, G2L)
4       0.75                                     (G6W)
11      0.75                               (Batter_SB)
25      0.75                                (G3W, G2L)
151     0.75                     (Batter_SB, G2L, G6W)
5       0.75                                     (G2L)
153     0.75                   (Dragons 1st, G2L, G6W)
24      0.75                                (G3W, G6W)
165     0.75             (Batter_SB, Dragons 1st, G6W)
406     0.75   (G3W, G2L, Batter_SB, Dragons 1st, G6W)
20      0.75                         (G1W, MVP_Batter)
12      0.75                              (MVP_Batter)
14      0.75                                (G1W, G3W)
21      0.75                        (G1W, Dragons 1st)
364     0.50   (G2L, G1W, Dragons 1st, Batter_SB, G6W)
390     0.50   (G3W, G2L, Batter_SB, Dragons 1st, G4W)
365     0.50  (G2L, G1W, Dragons 1st, G6W, MVP_Batter)
400     0.50       (G3W, G2L, Dragons 1st, S.H.C, G6W)
367     0.50   (G1W, Dragons 1st, Batter_SB, G5L, G6W)
399     0.50         (G3W, G2L, Batter_SB, S.H.C, G6W)
368     0.50  (G1W, Dragons 1st, G5L, G6W, MVP_Batter)